# Generated by Django 2.1.15 on 2020-09-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userlogindetails',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('usertype', models.CharField(blank=True, db_column='UserType', max_length=20, null=True)),
                ('loginid', models.BinaryField(blank=True, db_column='LoginID', null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('mobileno', models.CharField(blank=True, db_column='MobileNo', max_length=20, null=True)),
                ('landlineno', models.CharField(blank=True, db_column='LandLineNo', max_length=20, null=True)),
                ('emailaddress', models.CharField(db_column='EmailAddress', max_length=100, unique=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('enteredonmachineid', models.CharField(blank=True, db_column='EnteredOnMachineID', max_length=50, null=True)),
                ('exeversionno', models.CharField(blank=True, db_column='ExeVersionNo', max_length=50, null=True)),
                ('isapproved', models.BooleanField(blank=True, db_column='IsApproved', null=True)),
                ('approvedby', models.CharField(blank=True, db_column='ApprovedBy', max_length=50, null=True)),
                ('approvedon', models.DateTimeField(blank=True, db_column='ApprovedOn', null=True)),
                ('modulename', models.CharField(blank=True, db_column='ModuleName', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('salutation', models.CharField(blank=True, db_column='Salutation', max_length=10, null=True)),
                ('mbsn', models.BinaryField(blank=True, db_column='MBSN', null=True)),
                ('sysmodifieddatetime', models.DateTimeField(blank=True, db_column='SysModifiedDateTime', null=True)),
                ('publisheddatetime', models.DateTimeField(blank=True, db_column='PublishedDateTime', null=True)),
                ('isinternaluser', models.BooleanField(blank=True, db_column='IsInternalUser', null=True)),
                ('isruleeditable', models.BooleanField(blank=True, db_column='IsRuleEditable', null=True)),
            ],
            options={
                'db_table': 'UserLoginDetails',
                'managed': True,
            },
        ),
    ]
