# Generated by Django 2.1.15 on 2020-09-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pythonfunctionstable',
            fields=[
                ('pythonfunctionsid', models.CharField(db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('ruledetailsid', models.CharField(blank=True, db_column='RuleDetailsId', max_length=50, null=True)),
                ('taskid', models.IntegerField(blank=True, db_column='TaskID', null=True)),
                ('paramname', models.CharField(blank=True, db_column='ParamName', max_length=255, null=True)),
                ('paramvalue', models.CharField(blank=True, db_column='ParamValue', max_length=255, null=True)),
                ('pythonfunctionname', models.CharField(blank=True, db_column='PythonFunctionName', max_length=500, null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('exeversionno', models.CharField(blank=True, db_column='ExeVersionNo', max_length=50, null=True)),
                ('enteredonmachineid', models.CharField(blank=True, db_column='EnteredOnMachineID', max_length=50, null=True)),
                ('sysmodifieddatetime', models.DateTimeField(blank=True, db_column='SysModifiedDateTime', null=True)),
                ('publisheddatetime', models.DateTimeField(blank=True, db_column='PublishedDateTime', null=True)),
                ('task_id', models.CharField(blank=True, db_column='Task_ID', max_length=50, null=True)),
            ],
            options={
                'db_table': 'pythonfunctionstable',
            },
        ),
        migrations.CreateModel(
            name='Sessiontestmapping',
            fields=[
                ('sessiontestid', models.CharField(db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('ruledetailsid', models.CharField(db_column='RuleDetailsID', max_length=50)),
                ('userid', models.CharField(db_column='UserID', max_length=50)),
                ('sessionid', models.CharField(db_column='SessionID', max_length=100)),
                ('todolistid', models.CharField(db_column='ToDoListID', max_length=50)),
                ('ruleid', models.CharField(db_column='RuleID', max_length=150)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('exeversionno', models.CharField(blank=True, db_column='ExeVersionNo', max_length=50, null=True)),
                ('isapproved', models.BooleanField(blank=True, db_column='IsApproved', null=True)),
                ('approvedby', models.CharField(blank=True, db_column='ApprovedBy', max_length=100, null=True)),
                ('approvedon', models.DateTimeField(blank=True, db_column='ApprovedOn', null=True)),
                ('modulename', models.CharField(blank=True, db_column='ModuleName', max_length=100, null=True)),
                ('enteredonmachineid', models.CharField(blank=True, db_column='EnteredOnMachineID', max_length=50, null=True)),
                ('sysmodifieddatetime', models.DateTimeField(blank=True, db_column='SysModifiedDateTime', null=True)),
                ('publisheddatetime', models.DateTimeField(blank=True, db_column='PublishedDateTime', null=True)),
            ],
            options={
                'db_table': 'SessionTestMapping',
            },
        ),
        migrations.CreateModel(
            name='Storedproceduretable',
            fields=[
                ('storedproceduretableid', models.CharField(db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('ruledetailsid', models.CharField(blank=True, db_column='RuleDetailsId', max_length=50, null=True)),
                ('paramname', models.CharField(blank=True, db_column='ParamName', max_length=255, null=True)),
                ('paramvalue', models.CharField(blank=True, db_column='ParamValue', max_length=255, null=True)),
                ('storedprocname', models.CharField(blank=True, db_column='StoredProcName', max_length=500, null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('exeversionno', models.CharField(blank=True, db_column='ExeVersionNo', max_length=50, null=True)),
                ('enteredonmachineid', models.CharField(blank=True, db_column='EnteredOnMachineID', max_length=50, null=True)),
                ('sysmodifieddatetime', models.DateTimeField(blank=True, db_column='SysModifiedDateTime', null=True)),
                ('publisheddatetime', models.DateTimeField(blank=True, db_column='PublishedDateTime', null=True)),
            ],
            options={
                'db_table': 'storedproceduretable',
            },
        ),
    ]
